[package]
name = "backdown"
version = "0.0.1"
authors = ["Canop <cano.petrole@gmail.com>"]
edition = "2018"
description = "nothing yet"
repository = "https://github.com/Canop/backdown"
license = "MIT"
readme = "README.md"


[dependencies]
anyhow = "1.0"
crossbeam = "0.7"
fnv = "1.0.7"
phf = { version = "0.8", features = ["macros"] }
rayon = "1.3"
sha2 = "0.9"
